function findDuplicates(arr) {
    const duplicates = {};
    const seen = {};

    arr.forEach((item, index) => {
        if (seen[item] !== undefined) {
            if (!duplicates[item]) {
                duplicates[item] = [seen[item]];
            }
            duplicates[item].push(index);
        } else {
            seen[item] = index;
        }
    });

    return duplicates;
}

// Example usage:
const words = [
    "Apple",
    "Refrigerator",
    "Unicycle",
    "Garbage can",
    "Giraffe",
    "Conference",
    "Sand Castle",
    "Thermos",
    "Football Player",
    "Factory",
    "Sword",
    "Ceiling Fan",
    "Jump Rope",
    "Hurricane",
    "Dinner bell",
    "Grandfather Clock",
    "Jet",
    "Helicopter",
    "Karate",
    "Celery",
    "Martini",
    "Lake",
    "Oak Tree",
    "Skunk",
    "Grizzly Bear",
    "Globe",
    "Fishing",
    "Shampoo",
    "Dump Truck",
    "Candy Cane",
    "Pine Tree",
    "Ice cream Sandwich",
    "Revolving door",
    "Cupid",
    "Jesus Christ",
    "Sorority",
    "Teacher",
    "Fireman",
    "Doctor",
    "Big Toe",
    "Texas",
    "Pancakes",
    "Bacon and Eggs",
    "Bikini",
    "Starfish",
    "Pikachu",
    "Boxing",
    "Mailbox",
    "Medicine",
    "Pills",
    "Remote Control",
    "Comedy Mask",
    "Milk Jug",
    "Steak",
    "Biscut",
    "Cookie Jar",
    "Rhinocerus",
    "Unicorn",
    "Cockroach",
    "Cat",
    "Vampire",
    "Wizard",
    "Market",
    "Sushi",
    "Napkin",
    "Archery",
    "Hula Hoop",
    "Teeter Totter",
    "Hot Tub",
    "Drum Set",
    "T-Rex",
    "Magazine",
    "Lava Lamp",
    "Volcano",
    "Car accident",
    "Campfire",
    "Owl",
    "Rat",
    "Rattlesnake",
    "Gorilla",
    "Pine cone",
    "Submarine",
    "Street Lamp",
    "Breath Mint",
    "Party Hat",
    "Coffee Maker",
    "RV",
    "Sledgehammer",
    "Porcupine",
    "Easter Bunny",
    "Chili Dog",
    "Coffee cup",
    "Garage",
    "Milkshake",
    "Bank robber",
    "Dam",
    "Humpty Dumpty",
    "Power outlet",
    "Leapord",
    "Dragon",
    "Fox",
    "Church",
    "Wrench",
    "Wedding",
    "Spiral Staircase",
    "Hourglass",
    "Swimming Pool",
    "Broccoli",
    "Island",
    "Remote control",
    "Hand Sanitizer",
    "Slippers",
    "Dolphin",
    "Clarinet",
    "Haunted House",
    "Ghoul",
    "Wine",
    "Coronavirus",
    "Pear",
    "Big rig Truck",
    "Fire Alarm",
    "Bald Eagle",
    "Dragonfly",
    "Driftwood",
    "Spaghetti",
    "Bowling Pins",
    "Cheeseburger",
    "Pot of Gold",
    "Shark",
    "Airport",
    "Taxi",
    "Penguin",
    "Crossing Guard",
    "Tornado",
    "Earthquake",
    "Tsunami",
    "Fishing pole",
    "Dominoes",
    "Revolving Door",
    "Washing Machine",
    "Baby Duck",
    "Binoculars",
    "4-Leaf Clover",
    "Grill",
    "Birdhouse",
    "Bracelet",
    "Orange Juice",
    "Tounge",
    "Pushup",
    "Baby Carriage",
    "Tuxedo",
    "Axe",
    "Pillow",
    "Octopus",
    "Cardboard Box",
    "Seatbelt",
    "Cubbies",
    "Locker",
    "Spotlight",
    "Water Slide",
    "Sunscreen",
    "Georgia",
    "California",
    "Oklahoma",
    "Florida",
    "Swan Boat",
    "Funnel",
    "Maple Syrup",
    "Sauna",
    "Super scary face",
    "Lima beans",
    "Toilet",
    "Golf",
    "Elephant",
    "Pajamas",
    "Thimble",
    "Car Dealership",
    "Headphones",
    "Prickly Pear",
    "Donald Trump",
    "Starship",
    "New York City",
    "4 Seasons",
    "Soaker Hose",
    "Ballerina",
    "Bubbles",
    "Koala",
    "Train conductor",
    "Tractor",
    "Violin",
    "Fast Food",
    "Yawn",
    "Cough",
    "Sneeze",
    "Nightlight",
    "Castle",
    "Can of soda",
    "Fish in a bowl",
    "Alligator",
    "Fighter jet"
];
const result = findDuplicates(words);
console.log(result);